import {categories,colors,demo,validate,connected} from './model.mjs';
import {loadPortfolio,savePortfolio} from './portfolio.mjs';
import {setupEnhancements} from './enhancements.mjs';
import {attachCatalog} from './equipment-catalog.mjs';
const $=id=>document.getElementById(id),key='bring-building-atlas-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
let data=demo(),category='all',selected='pump',viewer,editing=null,portfolio,storageBlocked=false;
let state={floor:'all',transparent:true,explode:false,layers:new Set(categories.map(c=>c.id)),selected};
try{portfolio=loadPortfolio(localStorage);data=portfolio.items.find(i=>i.id===portfolio.activeId).data;}catch{storageBlocked=true;portfolio={version:2,activeId:'preview',items:[{id:'preview',data}]};$('storage').textContent='기존 저장 자료 읽기 실패 · 보호를 위해 저장 중지 · 백업 파일 확인 필요';}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000);}
function persist(next){validate(next);if(storageBlocked)throw Error('기존 자료를 읽을 수 없어 저장을 중지했습니다. 원본 데이터를 확인해주세요.');const p=structuredClone(portfolio);p.items.find(i=>i.id===p.activeId).data=next;try{savePortfolio(localStorage,p);}catch{throw Error('브라우저 저장공간이 부족하거나 저장이 차단되었습니다. 백업 후 다시 시도해주세요.');}portfolio=p;data=next;render();toast('이 브라우저에 저장했습니다.');}
function choose(id){selected=id;state.selected=id;render();}
function render(){
 $('title').textContent=data.building.name;$('address').textContent=data.building.address;$('stats').textContent=`지하 1층 + 지상 ${data.building.floors}층 · 등록 ${data.records.length}건 · 현장 확인 ${data.records.filter(r=>r.confidence==='현장 확인').length}건`;
 $('floor').innerHTML='<option value="all">전체 층</option>'+Array.from({length:data.building.floors+1},(_,f)=>`<option value="${f}">${f===0?'지하 1층':f+'층'}</option>`).join('');$('floor').value=state.floor;
 $('categories').innerHTML=[{id:'all',name:'전체 기록'},...categories].map(c=>`<button data-category="${c.id}" class="${category===c.id?'active':''}">${c.name}<span>${data.records.filter(r=>c.id==='all'||r.category===c.id).length}</span></button>`).join('');
 $('layers').innerHTML=categories.filter(c=>['building','water','electric','fire','hvac','sensor'].includes(c.id)).map(c=>`<label><input type="checkbox" data-layer="${c.id}" ${state.layers.has(c.id)?'checked':''}><span style="color:#${colors[c.id].toString(16).padStart(6,'0')}"> ● </span>${c.name}</label>`).join('');
 const q=$('search').value.toLowerCase(),rows=data.records.filter(r=>(category==='all'||r.category===category)&&(state.floor==='all'||r.floor===Number(state.floor))&&JSON.stringify(r).toLowerCase().includes(q));
 $('listTitle').textContent=categories.find(c=>c.id===category)?.name||'전체 기록';$('count').textContent=rows.length+'건';
 $('records').innerHTML=rows.length?rows.map(r=>`<button class="record ${r.id===selected?'selected':''}" data-record="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>${r.floor===0?'B1':r.floor+'F'} · ${esc(r.status)} · ${esc(r.confidence)}</small></button>`).join(''):'<p class="muted">등록된 기록이 없습니다. ‘＋ 기록 등록’에서 추가하세요.</p>';
 renderDetail();viewer?.update(data,state);document.dispatchEvent(new Event('atlas-render'));
}
function renderDetail(){const r=data.records.find(r=>r.id===selected);if(!r){$('detail').innerHTML='<h2>설비와 기록을 선택하세요</h2><p class="muted">3D 설비 또는 아래 목록에서 항목을 선택하면 연결 정보와 상세 기록을 확인할 수 있습니다.</p>';return;}
 const field=(k,v)=>`<dt>${esc(k)}</dt><dd>${esc(v||'등록 필요')}</dd>`;
 const photo=safeURL(r.photo),doc=safeURL(r.document);
 $('detail').innerHTML=`<span class="eyebrow">${esc(categories.find(c=>c.id===r.category).name)}</span><h2>${esc(r.name)}</h2><span class="badge">${esc(r.status)}</span><span class="badge">${esc(r.confidence)}</span><div class="buttons"><button id="editRecord" class="primary">정보 수정</button><button id="deleteRecord" class="danger">삭제</button></div>${photo?`<a href="${esc(photo)}" target="_blank" rel="noopener noreferrer">현장 사진 열기 ↗</a>`:''}<dl>${field('위치',`${r.floor===0?'지하 1':r.floor}층 · X ${r.x}m / Z ${r.z}m`)}${Object.entries(r.fields).map(([k,v])=>field(k,v)).join('')}${field('설명·작업 이력',r.notes)}${field('확인 근거',r.source)}${field('확인일',r.verifiedAt)}</dl>${doc?`<a href="${esc(doc)}" target="_blank" rel="noopener noreferrer">문서·도면 열기 ↗</a>`:''}<h2>연결된 설비·기록</h2><p class="muted">등록된 연결 관계입니다. 물리적 흐름·차단 가능 여부는 별도로 현장 확인해야 합니다.</p>${connected(data,r.id).filter(id=>id!==r.id).map(id=>{const x=data.records.find(v=>v.id===id);return `<button class="connection" data-record="${esc(id)}">${esc(x.name)} →</button>`;}).join('')||'<p class="muted">연결 없음</p>'}`;
 $('editRecord').onclick=()=>openRecord(r);$('deleteRecord').onclick=()=>{if(!confirm('이 기록을 삭제할까요? 연결도 함께 해제됩니다.'))return;const next=structuredClone(data);next.records=next.records.filter(v=>v.id!==r.id).map(v=>({...v,links:v.links.filter(id=>id!==r.id),...(v.routes?{routes:v.routes.filter(route=>route.targetId!==r.id)}:{})}));try{persist(next);}catch(e){toast(e.message);}};
}
const input=(name,label,value='',type='text',wide=false)=>`<label class="${wide?'wide':''}">${esc(label)}<input name="${esc(name)}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}"></label>`;
const area=(name,label,value='')=>`<label class="wide">${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;
function openRecord(record){editing=record?.id||'new';const r=record||{name:'',category:category==='all'?'water':category,floor:state.floor==='all'?0:Number(state.floor),x:0,z:0,status:'확인 필요',confidence:'추정',fields:{},links:[]};$('editorTitle').textContent=record?'기록 수정':'새 기록 등록';
 $('formFields').innerHTML=input('name','설비·기록 이름',r.name)+`<label>데이터 영역<select name="category">${categories.map(c=>`<option value="${c.id}" ${c.id===r.category?'selected':''}>${c.name}</option>`).join('')}</select></label>`+input('floor','층 (0 = 지하 1층)',r.floor,'number')+input('x','가로 위치 X (m)',r.x,'number')+input('z','세로 위치 Z (m)',r.z,'number')+`<label>상태<select name="status">${['정상','확인 필요','점검 필요','견적 대기','작업 중','긴급','완료'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><label>정보 확인 수준<select name="confidence">${['예시','추정','도면 확인','현장 확인'].map(s=>`<option ${s===r.confidence?'selected':''}>${s}</option>`).join('')}</select></label>`+input('verifiedAt','확인일',r.verifiedAt,'date')+input('source','확인 근거 (도면명·사진·담당자)',r.source,'text',true)+input('photo','현장 사진 URL',r.photo,'url',true)+input('document','문서·도면 URL',r.document,'url',true)+`<label class="wide">연결 설비·관련 기록 (Ctrl로 여러 항목 선택)<select name="links" multiple size="4">${data.records.filter(v=>v.id!==r.id).map(v=>`<option value="${esc(v.id)}" ${r.links.includes(v.id)?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><div class="wide muted" id="fieldGuide"></div>`+area('fields','상세 항목 (한 줄에 항목: 값)',Object.entries(r.fields).map(([k,v])=>`${k}: ${v}`).join('\n'))+area('notes','설명·작업 이력·추가 메모',r.notes);
 if(record){const hint=document.createElement('p');hint.className='wide muted';hint.textContent='층·좌표를 변경하면 확인 수준은 추정으로 바뀌고 확인일과 관련 경로의 확인 표시가 해제됩니다. 저장 후 현장에서 다시 확인해주세요.';$('formFields').prepend(hint);}
const guide=()=>{const c=categories.find(c=>c.id===$('form').elements.category.value);$('fieldGuide').textContent='권장 입력: '+c.fields.join(' · ');if(!$('form').elements.fields.value)$('form').elements.fields.value=c.fields.map(k=>k+': ').join('\n');};$('form').elements.category.onchange=guide;guide();attachCatalog($('form'),record,guide);$('formError').textContent='';$('editor').showModal();
}
function openBuilding(){editing='building';$('editorTitle').textContent='건물 설정';const b=data.building;$('formFields').innerHTML=input('name','건물명',b.name)+input('address','주소',b.address)+input('floors','지상 층수 (1~30)',b.floors,'number')+input('width','가로 (m)',b.width,'number')+input('depth','세로 (m)',b.depth,'number')+'<p class="wide muted">현재 모델은 지하 1개 층을 포함합니다. 실제 도면이 없으면 대략적인 치수를 입력하세요. 기존 설비가 새 크기를 벗어나면 위치를 먼저 수정해야 합니다.</p>';$('formError').textContent='';$('editor').showModal();}
$('form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),next=structuredClone(data);if(editing==='building'){next.building={...next.building,name:f.get('name').trim(),address:f.get('address'),floors:Number(f.get('floors')),width:Number(f.get('width')),depth:Number(f.get('depth'))};}else{const fields={};for(const line of f.get('fields').split('\n')){const i=line.indexOf(':');if(i>0){const k=line.slice(0,i).trim();if(!['__proto__','constructor','prototype'].includes(k))fields[k]=line.slice(i+1).trim();}}const r={...next.records.find(v=>v.id===editing),id:editing==='new'?crypto.randomUUID():editing,name:f.get('name').trim(),category:f.get('category'),shape:f.get('shape')||'',floor:Number(f.get('floor')),x:Number(f.get('x')),z:Number(f.get('z')),status:f.get('status'),confidence:f.get('confidence'),verifiedAt:f.get('verifiedAt'),source:f.get('source'),photo:f.get('photo'),document:f.get('document'),links:f.getAll('links'),notes:f.get('notes'),fields,updatedAt:new Date().toISOString()};if(r.routes)r.routes=r.routes.filter(route=>r.links.includes(route.targetId));const i=next.records.findIndex(v=>v.id===r.id);if(i<0)next.records.push(r);else {const previous=next.records[i];next.records[i]=r;if(['floor','x','z'].some(k=>previous[k]!==r[k])){r.confidence='추정';r.verifiedAt='';const notice='위치 변경 · 현장 재확인 필요';r.source=[r.source,notice].filter(Boolean).join(' / ');for(const record of next.records)for(const route of record.routes||[])if(record.id===r.id||route.targetId===r.id)route.confirmed=false;}}selected=r.id;state.selected=r.id;}persist(next);$('editor').close();}catch(e){$('formError').textContent=e.message;}};
 document.addEventListener('click',e=>{const item=e.target.closest('[data-record]');if(item)choose(item.dataset.record);const cat=e.target.closest('[data-category]');if(cat){category=cat.dataset.category;render();}});
 $('layers').onchange=e=>{const id=e.target.dataset.layer;if(id){e.target.checked?state.layers.add(id):state.layers.delete(id);viewer?.update(data,state);}};
 $('search').oninput=render;$('floor').onchange=e=>{state.floor=e.target.value;render();viewer?.reset();};$('shell').onchange=e=>{state.transparent=e.target.checked;viewer?.update(data,state);};$('explode').onchange=e=>{state.explode=e.target.checked;viewer?.update(data,state);viewer?.reset();};$('reset').onclick=()=>{state.floor='all';render();viewer?.reset();};$('add').onclick=()=>openRecord();$('buildingEdit').onclick=openBuilding;$('close').onclick=()=>$('editor').close();
 $('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bring-building-atlas-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>8e6)throw Error('8MB 이하 JSON 파일을 선택해주세요.');const next=validate(JSON.parse(await file.text()));if(!confirm('현재 건물 데이터를 가져온 파일로 교체할까요? 필요한 경우 먼저 백업하세요.'))return;state.floor='all';persist(next);viewer?.reset();}catch(e){toast(e.message);}finally{e.target.value='';}};
 setupEnhancements({getData:()=>data,getSelected:()=>selected,getViewer:()=>viewer,getState:()=>state,getPortfolio:()=>portfolio,save:persist,toast,choose,render,setPortfolio:p=>{if(storageBlocked)throw Error('저장 자료 확인이 필요합니다.');savePortfolio(localStorage,p);portfolio=p;data=p.items.find(i=>i.id===p.activeId).data;selected=data.records[0]?.id;state.selected=selected;state.floor='all';category='all';$('search').value='';render();viewer?.reset();}});
 render();try{const {createViewer}=await import('./viewer.mjs');viewer=createViewer($('viewport'),choose);viewer.update(data,state);viewer.reset();}catch(e){$('fallback').hidden=false;console.error('3D initialization failed',e);}
