import {validate} from './model.mjs';
import {maintenanceSummary} from './maintenance.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validateBackup(p){
 if(!p||p.version!==2||!Array.isArray(p.items)||p.items.length<1||p.items.length>100||typeof p.activeId!=='string')throw Error('최대 100개 건물을 포함한 전체 백업 파일을 선택해주세요.');
 const ids=new Set();for(const item of p.items){if(!item||typeof item.id!=='string'||!item.id||ids.has(item.id))throw Error('백업의 건물 번호가 올바르지 않습니다.');ids.add(item.id);validate(item.data);}if(!ids.has(p.activeId))throw Error('백업의 선택 건물이 없습니다.');return p;
}
export function mergeBackup(current,incoming,idFactory=()=>crypto.randomUUID()){
 validateBackup(incoming);const merged=structuredClone(current),ids=new Set(merged.items.map(i=>i.id));
 if(merged.items.length+incoming.items.length>100)throw Error('전체 건물은 최대 100개입니다.');
 for(const item of incoming.items){const copy=structuredClone(item);if(ids.has(copy.id)){copy.id=idFactory();if(ids.has(copy.id))throw Error('복사 건물 번호 충돌');copy.data.building.name=(copy.data.building.name.slice(0,135)+' · 복원 사본');}ids.add(copy.id);merged.items.push(copy);}return merged;
}
export function reportHTML(data,today=new Date().toLocaleDateString('sv-SE')){
 validate(data);const s=maintenanceSummary(data,today);const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">등록된 기록이 없습니다.</td></tr>`}</tbody></table></div>`;
 const costs=data.records.flatMap(r=>(r.history||[]).map(h=>[h.date,r.name,h.worker||'미입력',h.text,typeof h.cost==='number'&&Number.isFinite(h.cost)&&h.cost>=0?h.cost.toLocaleString('ko-KR')+'원':'미입력'])).sort((a,b)=>String(b[0]).localeCompare(String(a[0])));
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(data.building.name)} · 점검 보고서</title><style>body{font:14px/1.7 'Malgun Gothic',sans-serif;background:#edf2f8;color:#203650;margin:0}main{max-width:1080px;margin:30px auto;padding:40px;background:white;border-radius:16px}h1{font-size:28px;margin:10px 0}h2{font-size:19px;margin:32px 0 12px}small,.muted{color:#74869e}.brand{font-weight:bold;color:#2267c9;letter-spacing:2px}.warning{background:#fff4db;padding:12px;border-radius:8px}.metrics{display:flex;flex-wrap:wrap;gap:12px;margin:22px 0}.metrics div{flex:1;min-width:130px;padding:16px;background:#f0f5fd;border-radius:10px}.metrics strong{display:block;font-size:22px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid #dae4ef;vertical-align:top;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#ecf3fc}.table-wrap{overflow:auto}button{background:#2367d7;color:white;padding:10px 18px;border:0;border-radius:8px;cursor:pointer}footer{border-top:1px solid #dce6f1;margin-top:35px;padding-top:18px;font-size:12px}@media(max-width:600px){main{margin:0;padding:20px;border-radius:0}}@media print{body{background:white}main{margin:0;padding:0;max-width:none}button{display:none}thead{display:table-header-group}tr{break-inside:avoid}.table-wrap{overflow:visible}h2{break-after:avoid}@page{size:A4;margin:15mm}}</style></head><body><main><div class="brand">BRING · BUILDING ATLAS</div><h1>${esc(data.building.name)} 점검 보고서</h1><p>${esc(data.building.address||'주소 미입력')}<br><small>작성 기준 ${esc(today)} · 브라우저에 저장된 입력 기록 기준</small></p><button onclick="window.print()">인쇄 / PDF로 저장</button>${data.building.example?'<p class="warning">예시 건물의 가상 배치와 입력 기록입니다. 실제 현장 점검 실적으로 사용할 수 없습니다.</p>':''}<div class="metrics">${[['등록 설비',s.assets.length+'개'],['현장 미확인',s.unverified.length+'개'],['예정일 경과',s.overdue.length+'건'],['입력 수리비',s.recordedCost.toLocaleString('ko-KR')+'원']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><p class="muted">작업 기록 ${s.historyCount}건, 비용 미입력 ${s.missingCost}건. 수리비는 입력된 비용의 단순 합계입니다.</p><h2>1. 조치가 필요한 설비</h2>${table(['설비','층','상태','확인 수준','담당자'],s.attention.map(r=>[r.name,r.floor===0?'B1':r.floor+'F',r.status,r.confidence,r.assignee||'미지정']))}<h2>2. 점검 일정</h2>${table(['예정일','설비·기록','담당자','일정 상태'],s.scheduled.map(r=>[r.nextInspection,r.name,r.assignee||'미지정',r.nextInspection<today?'예정일 경과':r.nextInspection===today?'오늘':'예정']))}<h2>3. 작업 내역과 비용</h2>${table(['작업일','설비·기록','담당자','내용','입력 비용'],costs)}<h2>4. 설비대장과 확인 근거</h2>${table(['설비','위치','확인 수준','확인일','근거'],s.assets.map(r=>[r.name,`${r.floor===0?'B1':r.floor+'F'} · X ${r.x} / Z ${r.z}`,r.confidence,r.verifiedAt||'미입력',r.source||'미입력']))}<footer>이 문서는 입력 자료를 정리한 운영 보고서입니다. 실제 측정·법정점검·안전진단을 수행했다는 의미가 아닙니다. 임대차 상세와 사진·도면 원본은 이 보고서에 포함하지 않습니다.</footer></main></body></html>`;
}
