import {duplicateRecords,duplicable} from './duplicate.mjs';
export function setupDuplicate(api){
 const $=id=>document.getElementById(id),dialog=document.createElement('dialog');dialog.id='duplicateDialog';dialog.innerHTML='<form id="duplicateForm"><div class="modalhead"><h2>설비·층 배치 복제</h2><button id="duplicateClose" type="button">닫기</button></div><p id="duplicateSource"></p><label>복제 범위<select name="scope"><option value="single">선택한 설비·공간만</option><option value="floor">같은 층의 설비·공간 전체</option></select></label><label>배치할 층<select name="targetFloor"></select></label><p id="duplicatePreview" role="status"></p><p class="muted">3D 모양·위치와 입력 항목 이름을 복제합니다. 사진·문서·점검 이력·비용·임대차 값·점검 일정은 복사하지 않습니다. 복제 대상끼리의 연결만 유지하며 다른 층과의 연결은 직접 지정해야 합니다.</p><p id="duplicateError" role="alert"></p><button class="primary" type="submit">확인한 배치 복제</button></form>';document.body.append(dialog);
 let sourceId,buildingId;
 const source=()=>api.getData().records.find(r=>r.id===sourceId);
 const ids=()=>{const r=source();if(!r)return [];return $('duplicateForm').elements.scope.value==='floor'?api.getData().records.filter(x=>x.floor===r.floor&&duplicable(x)).map(x=>x.id):[r.id];};
 function preview(){const count=ids().length;$('duplicatePreview').textContent=`새로 생성될 설비·공간 ${count}개 · 확인 필요 상태로 등록됩니다.`;}
 function open(){const r=api.getData().records.find(r=>r.id===api.getSelected());if(!r||!duplicable(r)){api.toast('복제할 설비나 공간을 선택해주세요.');return;}sourceId=r.id;buildingId=api.getPortfolio().activeId;$('duplicateSource').textContent=`원본: ${r.floor===0?'B1':r.floor+'F'} · ${r.name}`;$('duplicateForm').elements.scope.value='single';$('duplicateForm').elements.targetFloor.replaceChildren();for(let f=0;f<=api.getData().building.floors;f++)if(f!==r.floor)$('duplicateForm').elements.targetFloor.add(new Option(f===0?'지하 1층':f+'층',String(f)));$('duplicateError').textContent='';preview();dialog.showModal();}
 $('duplicateClose').onclick=()=>dialog.close();$('duplicateForm').elements.scope.onchange=preview;
 $('duplicateForm').onsubmit=e=>{e.preventDefault();try{if(buildingId!==api.getPortfolio().activeId)throw Error('건물이 변경되었습니다.');const floor=Number(e.target.elements.targetFloor.value),result=duplicateRecords(api.getData(),ids(),floor);api.save(result.data);api.getState().floor=String(floor);api.choose(result.newIds[0]);api.getViewer()?.reset();dialog.close();api.toast(`${result.count}개를 복제했습니다. 외부 연결 ${result.skippedLinks}개는 재지정이 필요합니다.`);}catch(err){$('duplicateError').textContent=err.message;}};
 document.addEventListener('atlas-render',()=>{const r=api.getData().records.find(r=>r.id===api.getSelected());if(!r||!duplicable(r))return;const b=document.createElement('button');b.id='duplicateAsset';b.textContent='다른 층에 복제';b.onclick=open;$('detail').querySelector('.buttons')?.append(b);});
}
