const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader']});try{const p=await b.newPage({viewport:{width:1550,height:1080}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(((process.env.ATLAS_TEST_URL||'http://localhost:59483')+'/building-operations/'));await p.locator('#viewport canvas').waitFor();
 await p.locator('#addHistory').click();await p.locator('#atlasToolsForm [name=worker]').fill('검증 담당자');await p.locator('#atlasToolsForm [name=text]').fill('펌프 연결 확인');await p.locator('#atlasToolsForm [name=cost]').fill('12000');await p.locator('#atlasToolsForm button[type=submit]').click();assert(await p.locator('.history').innerText().then(t=>t.includes('12,000')));
 await p.locator('#routeEdit').click();await p.locator('[name=points]').fill('0, -3, 2\n0, -3, 0');await p.locator('#atlasToolsForm button[type=submit]').click();
 await p.locator('#attachPhoto').click();await p.locator('#atlasToolsForm [name=photo]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:await p.screenshot()});await p.locator('#atlasToolsForm button[type=submit]').click();await p.locator('.asset-photo').waitFor();
 await p.locator('#editRecord').click();await p.locator('#form [name=source]').fill('현장 확인 기록');await p.locator('#form button[type=submit]').click();const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('bring-building-atlas-portfolio-v2')));const pump=saved.items[0].data.records.find(r=>r.id==='pump');assert.equal(pump.history.length,1);assert.equal(pump.routes[0].points.length,2);assert(pump.photoData.startsWith('data:image/jpeg'));
 await p.locator('#newBuilding').click();await p.locator('#atlasToolsForm [name=name]').fill('두 번째 테스트 건물');await p.locator('#atlasToolsForm button[type=submit]').click();assert.equal(await p.locator('#count').innerText(),'0건');await p.locator('#buildingSelect').selectOption('first');await p.locator('[data-record=pump]').first().click();await p.locator('.history').waitFor();await p.reload();await p.locator('#viewport canvas').waitFor();assert.equal(await p.locator('#buildingSelect option').count(),2);
 await p.locator('#focusAsset').click();await p.locator('#isolateSystem').check();await p.waitForTimeout(1500);await p.screenshot({path:'building-atlas-improved.png'});await p.setViewportSize({width:390,height:844});await p.waitForTimeout(500);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await p.screenshot({path:'building-atlas-improved-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: multi-building isolation, photo attachment, history, route editing, preservation, reload, focus, mobile width');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
