import {setupFloorPlan} from './floor-plan.mjs';
import {setupSamples} from './sample-ui.mjs';
import {setupTour} from './guided-tour.mjs';
import {setupMaintenance} from './maintenance-ui.mjs';
import {setupBackupReport} from './backup-report-ui.mjs';
import {setupDuplicate} from './duplicate-ui.mjs';
import {setupCRMTransfer} from './crm-transfer-ui.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
export function setupEnhancements(api){
 const {getData,getSelected,getViewer,getState,getPortfolio,save,setPortfolio,toast,render}=api;
 const panel=document.createElement('div');panel.className='building-picker';panel.innerHTML='<label for="buildingSelect">관리 건물</label><select id="buildingSelect"></select><button id="newBuilding">＋ 건물 추가</button>';document.querySelector('aside').prepend(panel);
 setupCRMTransfer(api);
 const tools=document.createElement('div');tools.className='atlas-toolbar';tools.innerHTML='<button id="focusAsset">선택 설비 확대</button><label><input id="isolateSystem" type="checkbox"> 연결 계통만 보기</label><span id="coverage"></span>';$('viewport').after(tools);
 const dialog=document.createElement('dialog');dialog.id='atlasTools';dialog.innerHTML='<form id="atlasToolsForm"><div class="modalhead"><h2 id="toolTitle"></h2><button id="toolClose" type="button">닫기</button></div><div id="toolFields"></div><p id="toolError" role="alert"></p><button class="primary" type="submit">저장하기</button></form>';document.body.append(dialog);
 let submit;
 const input=(name,label,value='',type='text')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''}></label>`;
 const open=(title,html,fn)=>{$('toolTitle').textContent=title;$('toolFields').innerHTML=html;$('toolError').textContent='';submit=fn;dialog.showModal();};
 $('toolClose').onclick=()=>dialog.close();$('atlasToolsForm').onsubmit=async e=>{e.preventDefault();try{await submit(new FormData(e.target));dialog.close();}catch(err){$('toolError').textContent=err.message;}};
 $('buildingSelect').onchange=e=>{const p=structuredClone(getPortfolio());p.activeId=e.target.value;try{setPortfolio(p);}catch(err){toast(err.message);sync();}};
 $('newBuilding').onclick=()=>open('관리 건물 추가',input('name','건물명')+input('address','주소')+input('floors','지상 층수',4,'number')+input('width','가로 m',16,'number')+input('depth','세로 m',12,'number')+'<p class="muted">빈 설비지도로 시작합니다. 실제 자료를 바탕으로 설비를 등록하세요.</p>',f=>{const name=f.get('name').trim();if(!name)throw Error('건물명을 입력해주세요.');const p=structuredClone(getPortfolio()),id=crypto.randomUUID();p.items.push({id,data:{version:1,building:{name,address:f.get('address'),floors:Number(f.get('floors')),width:Number(f.get('width')),depth:Number(f.get('depth'))},records:[]}});p.activeId=id;setPortfolio(p);toast('새 건물을 추가했습니다.');});
 $('focusAsset').onclick=()=>{const id=getSelected();if(!getData().records.some(r=>r.id===id)){toast('먼저 설비를 선택해주세요.');return;}const state=getState(),r=getData().records.find(r=>r.id===id);state.layers.add(r.category);state.floor='all';render();getViewer()?.focus(id);};
 $('isolateSystem').onchange=e=>{getState().isolate=e.target.checked;render();};
 function selectedRecord(){return getData().records.find(r=>r.id===getSelected());}
 function changeRecord(id,fn){const next=structuredClone(getData()),r=next.records.find(r=>r.id===id);if(!r)throw Error('선택 기록이 없습니다.');fn(r);r.updatedAt=new Date().toISOString();save(next);}
 function editRoute(){const r=selectedRecord();if(!r)return;if(!r.links.length){toast('정보 수정에서 연결 설비를 먼저 지정해주세요.');return;}
 open('배관 경로 편집',`<label>시작 설비<select name="target">${r.links.map(id=>`<option value="${esc(id)}">${esc(getData().records.find(x=>x.id===id).name)}</option>`).join('')}</select></label><p class="muted">선택한 시작 설비에서 <b>${esc(r.name)}</b>까지 이동하는 중간 지점입니다. 한 줄에 ‘층, X, Z’를 입력하세요. 0층은 지하 1층입니다. 비우면 자동 직각 경로로 표시됩니다.</p><label>경유점<textarea name="points" rows="6" placeholder="0, 3, 2&#10;1, 3, 2"></textarea></label><label><input name="routeConfirmed" type="checkbox"> 이 경로를 현장에서 확인했습니다</label>`,f=>{const lines=f.get('points').split('\n').filter(l=>l.trim()),points=lines.map(l=>{const v=l.split(',').map(t=>t.trim());if(v.length!==3||v.some(s=>s===''))throw Error('각 줄에 층, X, Z 세 숫자를 입력해주세요.');return {floor:Number(v[0]),x:Number(v[1]),z:Number(v[2])};});changeRecord(r.id,x=>{x.routes=(x.routes||[]).filter(p=>p.targetId!==f.get('target'));if(points.length)x.routes.push({targetId:f.get('target'),points,confirmed:f.get('routeConfirmed')==='on'});});});
 const f=$('atlasToolsForm'),load=()=>{const route=(r.routes||[]).find(p=>p.targetId===f.elements.target.value);f.elements.routeConfirmed.checked=route?.confirmed===true;f.elements.points.value=(route?.points||[]).map(p=>`${p.floor}, ${p.x}, ${p.z}`).join('\n');};f.elements.target.onchange=load;load();
 }
 async function compressedPhoto(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('JPG, PNG, WebP 사진을 선택해주세요.');if(file.size>15e6)throw Error('15MB 이하 사진을 선택해주세요.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const url=c.toDataURL('image/jpeg',.72);if(url.length>800000)throw Error('사진 용량이 큽니다. 더 작은 사진을 선택해주세요.');return url;}
 function addPhoto(){const r=selectedRecord();if(!r)return;open('현장 사진 첨부','<label>사진 파일<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required></label><p class="muted">현재 설비의 대표 사진으로 저장됩니다. 기존 대표 사진이 있으면 교체합니다. 이 브라우저에 저장되며 건물 백업에 포함됩니다.</p>',async f=>{const url=await compressedPhoto(f.get('photo'));changeRecord(r.id,x=>x.photoData=url);});}
 function addHistory(){const r=selectedRecord();if(!r)return;open('점검·작업 기록 추가',input('date','작업일',new Date().toLocaleDateString('sv-SE'),'date')+input('worker','담당자')+'<label>작업 내용<textarea name="text" rows="4" required></textarea></label>'+input('cost','발생 비용 원','','number'),f=>{if(!f.get('date')||!f.get('text').trim())throw Error('날짜와 작업 내용을 입력해주세요.');const raw=f.get('cost'),cost=raw===''?null:Number(raw);if(cost!==null&&(!Number.isFinite(cost)||cost<0))throw Error('비용은 0 이상의 숫자입니다.');changeRecord(r.id,x=>{x.history=[{date:f.get('date'),worker:f.get('worker'),text:f.get('text').trim(),cost},...(x.history||[])];});});}
 function sync(){const p=getPortfolio();$('buildingSelect').innerHTML=p.items.map(i=>`<option value="${esc(i.id)}">${esc(i.data.building.name)}</option>`).join('');$('buildingSelect').value=p.activeId;const data=getData(),checked=data.records.filter(r=>r.confidence==='현장 확인').length;$('coverage').textContent=`현장 확인 ${checked} / ${data.records.length}건`;
 const r=selectedRecord();if(!r)return;const detail=$('detail'),section=document.createElement('section');section.className='equipment-work';section.innerHTML=`${r.photoData?`<img class="asset-photo" alt="${esc(r.name)} 현장 사진" src="${esc(r.photoData)}">`:'<div class="photo-empty">현장 사진을 첨부하면 이곳에서 바로 확인할 수 있습니다.</div>'}<div class="quick-actions"><button id="attachPhoto">사진 첨부</button><button id="routeEdit">배관 경로</button><button id="addHistory">점검 기록</button></div><h3>최근 점검·작업</h3>${r.history?.length?r.history.slice(0,5).map(h=>`<article class="history"><small>${esc(h.date)} · ${esc(h.worker||'담당 미입력')}</small><p>${esc(h.text)}</p>${h.cost!==null&&h.cost!==undefined?`<b>${Number(h.cost).toLocaleString('ko-KR')}원</b>`:''}</article>`).join(''):'<p class="muted">아직 점검 기록이 없습니다.</p>'}`;detail.querySelector('.buttons').after(section);$('attachPhoto').onclick=addPhoto;$('routeEdit').onclick=editRoute;$('addHistory').onclick=addHistory;
 }
 document.addEventListener('atlas-render',sync);setupFloorPlan(api);setupSamples(api);setupTour(api);setupMaintenance(api);setupBackupReport(api);setupDuplicate(api);
}
