import {toPlan,toWorld} from './plan-coordinates.mjs';
import {colors} from './model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupFloorPlan(api){
 const $=id=>document.getElementById(id);
 const button=document.createElement('button');button.id='openFloorPlan';button.textContent='평면도에서 배치';document.querySelector('.atlas-toolbar').prepend(button);
 const dialog=document.createElement('dialog');dialog.id='floorPlanEditor';dialog.innerHTML=`<div class="modalhead"><div><span class="eyebrow">FLOOR PLAN · 설비 배치</span><h2>평면도에서 설비와 배관 지정</h2></div><button id="planClose">닫기</button></div><div class="plan-layout"><div class="plan-options"><label>층<select id="planFloor"></select></label><label>설비·기록<select id="planAsset"></select></label><label>작업<select id="planMode"><option value="position">설비 위치 지정</option><option value="route">배관 경로 지정</option></select></label><label id="planSourceLabel">연결 시작 설비<select id="planSource"></select></label><label class="upload-plan">도면 이미지<input id="planImage" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="muted">건물 외곽에 맞춰 여백을 잘라낸 도면을 사용하세요. 이미지 전체가 건물 가로·세로에 대응합니다. 도면 없이도 배치할 수 있습니다.</p><button id="planRemoveImage">이 층 도면 제거</button><button id="planUndo">마지막 경유점 취소</button><button id="planClearRoute">이 연결 경유점 비우기</button><p id="planSummary" class="muted"></p><label id="planConfirmation"><input id="planConfirmed" type="checkbox"> 이 배관 경로를 현장에서 확인함</label></div><div class="plan-stage"><p id="planHint"></p><canvas id="planCanvas" width="1000" height="750" tabindex="0" aria-label="층 평면도. 클릭하여 위치 지정. 아래 숫자 입력으로도 지정할 수 있습니다."></canvas><div class="plan-coordinate"><label>X (m)<input id="planX" type="number" step="0.01"></label><label>Z (m)<input id="planZ" type="number" step="0.01"></label><button id="planApplyCoordinate">좌표 적용</button></div><p id="planReadout" role="status"></p></div></div><div class="plan-footer"><span id="planError" role="alert"></span><button id="planSave" class="primary">변경사항 저장 · 3D 반영</button></div>`;document.body.append(dialog);
 const canvas=$('planCanvas'),ctx=canvas.getContext('2d');let draft,assetId,floor=0,mode='position',source='',imageCache=new Map(),generation=0,busy=false;
 const asset=()=>draft.records.find(r=>r.id===assetId);
 const route=()=>asset()?.routes?.find(r=>r.targetId===source);
 function ensureRoute(){const r=asset();if(!r||!source)throw Error('연결된 설비를 먼저 선택해주세요.');r.routes??=[];let path=route();if(!path){path={targetId:source,points:[],confirmed:false};r.routes.push(path);}return path;}
 function rect(){const w=draft.building.width,h=draft.building.depth,scale=Math.min(900/w,620/h);return {x:(1000-w*scale)/2,y:(750-h*scale)/2,w:w*scale,h:h*scale};}
 function xy(p){const r=rect(),n=toPlan(p,draft.building);return {x:r.x+n.u*r.w,y:r.y+n.v*r.h};}
 function updateControls(){
 const r=asset();$('planSource').innerHTML=(r?.links||[]).map(id=>`<option value="${esc(id)}">${esc(draft.records.find(x=>x.id===id)?.name)}</option>`).join('');if(!r?.links.includes(source))source=r?.links[0]||'';$('planSource').value=source;
 $('planSourceLabel').hidden=mode!=='route';$('planConfirmation').hidden=mode!=='route';$('planConfirmed').checked=route()?.confirmed===true;
 $('planUndo').disabled=mode!=='route'||!route()?.points.length;$('planClearRoute').disabled=mode!=='route'||!route()?.points.length;
 $('planSummary').textContent=mode==='route'?`경유점 ${route()?.points.length||0}개 · 시작 설비 → 경유점 → 선택 설비`:`선택: ${r?.name||'설비 미등록'} · ${r?.floor===0?'B1':r?.floor+'F'}`;
 $('planHint').textContent=mode==='route'?'배관이 꺾이는 지점을 순서대로 클릭하세요. 층을 바꾸며 수직 경로도 지정할 수 있습니다.':'선택한 설비를 놓을 위치를 클릭하세요. 저장하면 3D 위치에 반영됩니다.';
 $('planReadout').textContent=`${draft.building.width}m × ${draft.building.depth}m · 위쪽 -Z / 오른쪽 +X · ${draft.building.floorPlans?.[floor]?.name||'도면 미등록 · 기본 격자'}`;
 if(r){$('planX').value=r.x;$('planZ').value=r.z;}draw();
 }
 function draw(){if(!draft)return;ctx.clearRect(0,0,1000,750);ctx.fillStyle='#f0f5fb';ctx.fillRect(0,0,1000,750);const box=rect();ctx.fillStyle='white';ctx.fillRect(box.x,box.y,box.w,box.h);const img=draft.building.floorPlans?.[floor]?.image;
 if(img){const cached=imageCache.get(img);if(cached)ctx.drawImage(cached,box.x,box.y,box.w,box.h);else{const g=generation,image=new Image();image.onload=()=>{if(g!==generation)return;imageCache.set(img,image);draw();};image.src=img;}}
 ctx.strokeStyle='#d6e2ef';ctx.lineWidth=1;for(let i=0;i<=10;i++){ctx.beginPath();ctx.moveTo(box.x+i*box.w/10,box.y);ctx.lineTo(box.x+i*box.w/10,box.y+box.h);ctx.moveTo(box.x,box.y+i*box.h/10);ctx.lineTo(box.x+box.w,box.y+i*box.h/10);ctx.stroke();}ctx.strokeStyle='#6485a5';ctx.lineWidth=2;ctx.strokeRect(box.x,box.y,box.w,box.h);
 for(const room of draft.records.filter(r=>r.floor===floor&&r.room)){const p=xy(room),w=room.room.width/draft.building.width*box.w,h=room.room.depth/draft.building.depth*box.h;ctx.fillStyle='#dcf2e333';ctx.fillRect(p.x-w/2,p.y-h/2,w,h);ctx.strokeStyle='#89a6ba';ctx.lineWidth=2;ctx.strokeRect(p.x-w/2,p.y-h/2,w,h);}
 const r=asset(),path=route();if(r&&path){const src=draft.records.find(x=>x.id===source),points=[src,...path.points,r];ctx.strokeStyle='#1683ee';ctx.lineWidth=4;ctx.setLineDash(path.confirmed?[]:[9,7]);for(let i=1;i<points.length;i++){if(points[i-1]?.floor!==floor||points[i]?.floor!==floor)continue;const a=xy(points[i-1]),b=xy(points[i]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.setLineDash([]);path.points.forEach((p,i)=>{if(p.floor!==floor)return;const q=xy(p);ctx.fillStyle='#1c79de';ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#153657';ctx.font='18px sans-serif';ctx.fillText(String(i+1),q.x+12,q.y-10);});}
 for(const item of draft.records.filter(x=>x.floor===floor)){const p=xy(item);ctx.beginPath();ctx.arc(p.x,p.y,item.id===assetId?12:8,0,Math.PI*2);ctx.fillStyle='#'+colors[item.category].toString(16).padStart(6,'0');ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=item.id===assetId?'#112f51':'white';ctx.stroke();ctx.font='bold 17px sans-serif';const text=item.name.slice(0,24),tw=ctx.measureText(text).width;let x=Math.min(p.x+15,990-tw),y=Math.max(24,p.y-12);ctx.fillStyle='#ffffffdf';ctx.fillRect(x-3,y-19,tw+6,24);ctx.fillStyle='#173855';ctx.fillText(text,x,y);}
 }
 function apply(p){$('planError').textContent='';try{const r=asset();if(!r)throw Error('먼저 기록 등록에서 설비를 추가해주세요.');if(!Number.isFinite(p.x)||!Number.isFinite(p.z)||Math.abs(p.x)>draft.building.width/2||Math.abs(p.z)>draft.building.depth/2)throw Error('좌표가 건물 범위를 벗어났습니다.');if(mode==='position'){Object.assign(r,p);r.confidence='추정';r.verifiedAt='';r.source='평면 배치에서 위치 변경 · 현장 재확인 필요';for(const v of draft.records)for(const path of v.routes||[])if(v.id===r.id||path.targetId===r.id)path.confirmed=false;}else{const path=ensureRoute();if(path.points.length>=100)throw Error('경유점은 최대 100개입니다.');path.points.push(p);path.confirmed=false;}r.updatedAt=new Date().toISOString();updateControls();}catch(e){$('planError').textContent=e.message;}}
 button.onclick=()=>{draft=structuredClone(api.getData());generation++;imageCache.clear();assetId=draft.records.some(r=>r.id===api.getSelected())?api.getSelected():draft.records[0]?.id;floor=asset()?.floor||0;mode='position';source='';$('planError').textContent='';$('planMode').value=mode;$('planFloor').innerHTML=Array.from({length:draft.building.floors+1},(_,f)=>`<option value="${f}">${f===0?'지하 1층':f+'층'}</option>`).join('');$('planFloor').value=String(floor);$('planAsset').innerHTML=draft.records.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('planAsset').value=assetId||'';dialog.showModal();updateControls();};
 $('planClose').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{generation++;draft=null;imageCache.clear();});
 $('planFloor').onchange=e=>{floor=Number(e.target.value);updateControls();};$('planAsset').onchange=e=>{assetId=e.target.value;source='';if(mode==='position'){floor=asset().floor;$('planFloor').value=String(floor);}updateControls();};$('planMode').onchange=e=>{mode=e.target.value;updateControls();};$('planSource').onchange=e=>{source=e.target.value;updateControls();};
 canvas.onclick=e=>{const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*1000,y=(e.clientY-b.top)/b.height*750,r=rect();if(x<r.x||x>r.x+r.w||y<r.y||y>r.y+r.h)return;apply(toWorld((x-r.x)/r.w,(y-r.y)/r.h,draft.building,floor));};
 $('planApplyCoordinate').onclick=()=>{if(!$('planX').value||!$('planZ').value){$('planError').textContent='X와 Z 좌표를 입력해주세요.';return;}apply({floor,x:Number($('planX').value),z:Number($('planZ').value)});};
 $('planUndo').onclick=()=>{const p=route();if(p){p.points.pop();p.confirmed=false;updateControls();}};$('planClearRoute').onclick=()=>{const r=asset();if(r){r.routes=(r.routes||[]).filter(p=>p.targetId!==source);updateControls();}};$('planConfirmed').onchange=e=>{try{ensureRoute().confirmed=e.target.checked;draw();}catch(err){e.target.checked=false;$('planError').textContent=err.message;}};
 $('planRemoveImage').onclick=()=>{if(draft.building.floorPlans)delete draft.building.floorPlans[floor];updateControls();};
 $('planImage').onchange=async e=>{const file=e.target.files[0],g=generation,targetFloor=floor;if(!file)return;busy=true;$('planSave').disabled=true;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15e6)throw Error('15MB 이하 JPG·PNG·WebP 도면을 선택해주세요.');const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*ratio));c.height=Math.max(1,Math.round(bitmap.height*ratio));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const image=c.toDataURL('image/jpeg',.8);if(image.length>1200000)throw Error('더 작은 도면 이미지를 선택해주세요.');if(g!==generation||!draft)return;draft.building.floorPlans??={};draft.building.floorPlans[targetFloor]={name:file.name,image,updatedAt:new Date().toISOString()};updateControls();}catch(err){if(g===generation)$('planError').textContent=err.message;}finally{busy=false;$('planSave').disabled=false;e.target.value='';}};
 $('planSave').onclick=()=>{if(busy)return;try{api.save(draft);api.getState().floor='all';api.render();api.getViewer()?.reset();dialog.close();}catch(e){$('planError').textContent=e.message;}};
}
