import {maintenanceSummary,validDate} from './maintenance.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupMaintenance(api){
 const $=id=>document.getElementById(id),button=document.createElement('button');button.id='maintenanceOverview';button.textContent='점검 현황';document.querySelector('.actions').prepend(button);
 const dialog=document.createElement('dialog');dialog.id='maintenanceDialog';dialog.innerHTML='<div class="modalhead"><h2 id="maintenanceTitle">건물 점검 현황</h2><button id="maintenanceClose">닫기</button></div><p id="maintenanceContext" class="muted"></p><div id="maintenanceMetrics"></div><div class="maintenance-filters"><button data-maintenance-filter="attention">조치 필요</button><button data-maintenance-filter="unverified">현장 미확인</button><button data-maintenance-filter="overdue">예정일 경과</button><button data-maintenance-filter="scheduled">점검 일정 전체</button></div><div id="maintenanceList"></div><p class="muted">일정은 직접 등록한 날짜 기준입니다. 점검 기록을 추가해도 다음 점검일은 자동 변경되지 않습니다.</p>';document.body.append(dialog);
 const editor=document.createElement('dialog');editor.id='inspectionEditor';editor.innerHTML='<form id="inspectionForm"><div class="modalhead"><h2>다음 점검 일정</h2><button id="inspectionClose" type="button">닫기</button></div><p id="inspectionAsset"></p><label>다음 점검일<input name="nextInspection" type="date"></label><label>담당자·업체<input name="assignee" type="text" maxlength="150"></label><p class="muted">점검일을 비워 저장하면 예약을 해제합니다. 자동 알림 발송은 연결 전입니다.</p><p id="inspectionError" role="alert"></p><button class="primary" type="submit">일정 저장</button></form>';document.body.append(editor);
 let filter='attention',editingId,editingBuilding;
 function overview(){const d=api.getData(),s=maintenanceSummary(d);$('maintenanceTitle').textContent=d.building.name+' · 점검 현황';$('maintenanceContext').textContent=d.building.example?'예시 건물의 입력 기록을 집계합니다. 실제 현장 실적이 아닙니다.':'현재 브라우저에 입력된 기록을 집계합니다.';
 $('maintenanceMetrics').innerHTML=[['등록 설비',s.assets.length+'개'],['현장 미확인',s.unverified.length+'개'],['예정일 경과',s.overdue.length+'건'],['오늘 점검',s.dueToday.length+'건'],['입력된 수리비',s.recordedCost.toLocaleString('ko-KR')+'원']].map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('');
 const rows=s[filter]||[];$('maintenanceList').innerHTML=rows.length?`<table><thead><tr><th>설비·기록</th><th>상태</th><th>다음 점검</th><th>담당</th><th>실행</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button data-maintenance-open="${esc(r.id)}">${esc(r.name)}</button><small>${r.floor===0?'B1':r.floor+'F'} · ${esc(r.confidence)}</small></td><td>${esc(r.status)}</td><td>${esc(r.nextInspection||'미등록')}</td><td>${esc(r.assignee||'미지정')}</td><td><button data-maintenance-schedule="${esc(r.id)}">일정 설정</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty-maintenance">이 조건에 해당하는 기록이 없습니다.</p>';
 for(const b of dialog.querySelectorAll('[data-maintenance-filter]'))b.classList.toggle('primary',b.dataset.maintenanceFilter===filter);
 const note=document.createElement('p');note.className='muted';note.textContent=`작업 기록 ${s.historyCount}건 · 비용 미입력 ${s.missingCost}건. 수리비는 입력된 작업 비용의 단순 합계이며 미입력 비용은 포함하지 않습니다.`;$('maintenanceMetrics').after(note);dialog.querySelectorAll('#maintenanceMetrics ~ p.metrics-note').forEach(n=>n.remove());note.classList.add('metrics-note');
 }
 function schedule(id){const r=api.getData().records.find(r=>r.id===id);if(!r)return;editingId=id;editingBuilding=api.getPortfolio().activeId;$('inspectionAsset').textContent=r.name;$('inspectionForm').elements.nextInspection.value=r.nextInspection||'';$('inspectionForm').elements.assignee.value=r.assignee||'';$('inspectionError').textContent='';editor.showModal();}
 button.onclick=()=>{overview();dialog.showModal();};$('maintenanceClose').onclick=()=>dialog.close();$('inspectionClose').onclick=()=>editor.close();
 dialog.onclick=e=>{const filterButton=e.target.closest('[data-maintenance-filter]');if(filterButton){filter=filterButton.dataset.maintenanceFilter;overview();}const open=e.target.closest('[data-maintenance-open]');if(open){const r=api.getData().records.find(r=>r.id===open.dataset.maintenanceOpen);if(r){dialog.close();api.getState().floor='all';api.getState().layers.add(r.category);api.choose(r.id);api.getViewer()?.focus(r.id);}}const edit=e.target.closest('[data-maintenance-schedule]');if(edit)schedule(edit.dataset.maintenanceSchedule);};
 $('inspectionForm').onsubmit=e=>{e.preventDefault();try{if(editingBuilding!==api.getPortfolio().activeId)throw Error('건물이 변경되었습니다. 다시 선택해주세요.');const f=new FormData(e.target),date=f.get('nextInspection');if(date&&!validDate(date))throw Error('유효한 점검일을 입력해주세요.');const d=structuredClone(api.getData()),r=d.records.find(r=>r.id===editingId);if(!r)throw Error('설비 기록을 찾을 수 없습니다.');r.nextInspection=date;r.assignee=f.get('assignee').trim();api.save(d);editor.close();if(dialog.open)overview();}catch(err){$('inspectionError').textContent=err.message;}};
 document.addEventListener('atlas-render',()=>{const r=api.getData().records.find(r=>r.id===api.getSelected());if(!r)return;const section=document.createElement('div');section.className='inspection-summary';const b=document.createElement('button');b.id='scheduleInspection';b.textContent='다음 점검 설정';b.onclick=()=>schedule(r.id);const text=document.createElement('p');text.textContent=`다음 점검: ${r.nextInspection||'미등록'} · 담당: ${r.assignee||'미지정'}`;section.append(text,b);$('detail').querySelector('.buttons')?.after(section);});
}
